---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit:
  - У пользователя должна быть возможность оставить контактные данные для оформления заказа
  - Сайт должен иметь поддержку клиентов через чат, email или телефон
  - При выборе английского языка все информация о товаре должна быть на английском языке, а цены должны быть в долларах
  - При выборе русского языка все информация о товаре должна быть на русском языке, а цены должны пересчитываться в рубли по актуальному курсу 
